.MODEL SMALL
.STACK 100H
.DATA

VOW DB 'AEIOUaeiou $'
MSG DB "ENTER THE STRING : $" 
 P1 LABEL BYTE
 M1 DB 0FFH
 L1 DB ?
STR DB 0FFH DUP ('$')  ;STORES COPY OF INPUT STRING
MSG3 DB 10,13,"NO OF VOWELS : $"    
  
.CODE

MOV AX,@DATA
MOV DS,AX
MOV ES,AX   ; FOR SCASB N REPNE

LEA DX,MSG
MOV AH,09
INT 21H

LEA DX,P1   ;READ INPUT STRING
MOV AH,0AH
INT 21H  

MOV DL,00
MOV BL,L1 ;STRING LENGTH
LEA SI,STR             ;INPUT STRING TO SI

LOOP:   MOV CX,000BH
        LODSB          ;COPY SI TO AL AND UPDATE SI
        LEA DI,VOW     ;VOWEL ARRAY
        REPNE SCASB    ;REPEATS COMPARISON B/W DI AND AL UNTIL EQUAL MAX CX TIMES AND DI IS UPDATED EACH TIME KEEPING AL INTACT 
        CMP CX,00
        JZ NOVOWEL
        INC DL
        
NOVOWEL: DEC BL
         JNZ LOOP 
                     
MOV BL,DL  ; COPYING VOWEL COUNT 

MOV AH,09H
LEA DX,MSG3
INT 21H

MOV AH,02     ;PRINTING VOWEL COUNT
MOV DL,BL
ADD DL,30H
INT 21H  

.EXIT 
END